# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qbert0g/proto/entropy_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'qbert0g/proto/entropy_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#qbert0g/proto/entropy_service.proto\x12\nqr_entropy\";\n\x0e\x45ntropyRequest\x12\x14\n\x0c\x62ytes_needed\x18\x01 \x01(\x05\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x03\"h\n\x0f\x45ntropyResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x03\x12\x1f\n\x17generation_timestamp_ns\x18\x03 \x01(\x03\x12\x11\n\tdevice_id\x18\x04 \x01(\t2\xa5\x01\n\x0e\x45ntropyService\x12\x45\n\nGetEntropy\x12\x1a.qr_entropy.EntropyRequest\x1a\x1b.qr_entropy.EntropyResponse\x12L\n\rStreamEntropy\x12\x1a.qr_entropy.EntropyRequest\x1a\x1b.qr_entropy.EntropyResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qbert0g.proto.entropy_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTROPYREQUEST']._serialized_start=51
  _globals['_ENTROPYREQUEST']._serialized_end=110
  _globals['_ENTROPYRESPONSE']._serialized_start=112
  _globals['_ENTROPYRESPONSE']._serialized_end=216
  _globals['_ENTROPYSERVICE']._serialized_start=219
  _globals['_ENTROPYSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
