# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qbert0g.proto import entropy_service_pb2 as qbert0g_dot_proto_dot_entropy__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qbert0g/proto/entropy_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EntropyServiceStub:
    """Entropy generation service.

    Provides random bytes on demand, with three transport modes:
    - GetEntropy (unary): simplest, one request → one response
    - StreamEntropy (bidirectional): persistent stream for lowest latency

    All modes satisfy the just-in-time constraint: entropy is generated
    only after the client sends a request.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEntropy = channel.unary_unary(
                '/qr_entropy.EntropyService/GetEntropy',
                request_serializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyRequest.SerializeToString,
                response_deserializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyResponse.FromString,
                _registered_method=True)
        self.StreamEntropy = channel.stream_stream(
                '/qr_entropy.EntropyService/StreamEntropy',
                request_serializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyRequest.SerializeToString,
                response_deserializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyResponse.FromString,
                _registered_method=True)


class EntropyServiceServicer:
    """Entropy generation service.

    Provides random bytes on demand, with three transport modes:
    - GetEntropy (unary): simplest, one request → one response
    - StreamEntropy (bidirectional): persistent stream for lowest latency

    All modes satisfy the just-in-time constraint: entropy is generated
    only after the client sends a request.

    """

    def GetEntropy(self, request, context):
        """Simple request-response (unary mode).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEntropy(self, request_iterator, context):
        """Persistent bidirectional stream (bidi and server-streaming modes).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntropyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEntropy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntropy,
                    request_deserializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyRequest.FromString,
                    response_serializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyResponse.SerializeToString,
            ),
            'StreamEntropy': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEntropy,
                    request_deserializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyRequest.FromString,
                    response_serializer=qbert0g_dot_proto_dot_entropy__service__pb2.EntropyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qr_entropy.EntropyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qr_entropy.EntropyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EntropyService:
    """Entropy generation service.

    Provides random bytes on demand, with three transport modes:
    - GetEntropy (unary): simplest, one request → one response
    - StreamEntropy (bidirectional): persistent stream for lowest latency

    All modes satisfy the just-in-time constraint: entropy is generated
    only after the client sends a request.

    """

    @staticmethod
    def GetEntropy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qr_entropy.EntropyService/GetEntropy',
            qbert0g_dot_proto_dot_entropy__service__pb2.EntropyRequest.SerializeToString,
            qbert0g_dot_proto_dot_entropy__service__pb2.EntropyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEntropy(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/qr_entropy.EntropyService/StreamEntropy',
            qbert0g_dot_proto_dot_entropy__service__pb2.EntropyRequest.SerializeToString,
            qbert0g_dot_proto_dot_entropy__service__pb2.EntropyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
