# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qbert0g/proto/purity_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'qbert0g/proto/purity_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"qbert0g/proto/purity_service.proto\x12\tqr_purity\"J\n\x0b\x44rawRequest\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x03\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x13\n\x0b\x62lock_bytes\x18\x03 \x01(\r\"\xf4\x01\n\x0c\x44rawResponse\x12\t\n\x01u\x18\x01 \x01(\x01\x12\t\n\x01z\x18\x02 \x01(\x01\x12\x13\n\x0bsequence_id\x18\x03 \x01(\x03\x12\x1f\n\x17generation_timestamp_ns\x18\x04 \x01(\x04\x12\x11\n\tsource_id\x18\x05 \x01(\t\x12\x13\n\x0b\x63oherence_z\x18\x06 \x01(\x01\x12\x17\n\x0f\x63oherence_valid\x18\x07 \x01(\x08\x12\x14\n\x0cpurity_label\x18\x08 \x01(\t\x12\x18\n\x10integrated_bytes\x18\t \x01(\r\x12\x12\n\nintegrator\x18\n \x01(\t\x12\x13\n\x0b\x63oherence_r\x18\x0b \x01(\x01\x32\x8f\x01\n\rPurityService\x12:\n\x07GetDraw\x12\x16.qr_purity.DrawRequest\x1a\x17.qr_purity.DrawResponse\x12\x42\n\x0bStreamDraws\x12\x16.qr_purity.DrawRequest\x1a\x17.qr_purity.DrawResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qbert0g.proto.purity_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRAWREQUEST']._serialized_start=49
  _globals['_DRAWREQUEST']._serialized_end=123
  _globals['_DRAWRESPONSE']._serialized_start=126
  _globals['_DRAWRESPONSE']._serialized_end=370
  _globals['_PURITYSERVICE']._serialized_start=373
  _globals['_PURITYSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
