# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qbert0g.proto import purity_service_pb2 as qbert0g_dot_proto_dot_purity__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qbert0g/proto/purity_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PurityServiceStub:
    """Server-side integrated draw service (the QPI layer).

    One draw = one freshly measured raw block, integrated server-side
    against the source's frozen fingerprint baseline into a z-score and
    a uniform value u = Phi(z), served together with the device-pair
    coherence snapshot and the source's canonical purity label.

    Invariants carried over from the entropy seam:
    - sequence_id is echoed verbatim (commitment-nonce echo);
    - a success response never carries u outside (0, 1) — the server
    clamps to (1e-10, 1 - 1e-10), so u = 0.0 on the wire is
    unambiguously "absent";
    - coherence_valid = false whenever the coherence gate cannot be
    computed (monitor disabled, stale, or never computed) — never a
    fake zero.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDraw = channel.unary_unary(
                '/qr_purity.PurityService/GetDraw',
                request_serializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawRequest.SerializeToString,
                response_deserializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawResponse.FromString,
                _registered_method=True)
        self.StreamDraws = channel.stream_stream(
                '/qr_purity.PurityService/StreamDraws',
                request_serializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawRequest.SerializeToString,
                response_deserializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawResponse.FromString,
                _registered_method=True)


class PurityServiceServicer:
    """Server-side integrated draw service (the QPI layer).

    One draw = one freshly measured raw block, integrated server-side
    against the source's frozen fingerprint baseline into a z-score and
    a uniform value u = Phi(z), served together with the device-pair
    coherence snapshot and the source's canonical purity label.

    Invariants carried over from the entropy seam:
    - sequence_id is echoed verbatim (commitment-nonce echo);
    - a success response never carries u outside (0, 1) — the server
    clamps to (1e-10, 1 - 1e-10), so u = 0.0 on the wire is
    unambiguously "absent";
    - coherence_valid = false whenever the coherence gate cannot be
    computed (monitor disabled, stale, or never computed) — never a
    fake zero.

    """

    def GetDraw(self, request, context):
        """Simple request-response (unary mode).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDraws(self, request_iterator, context):
        """Persistent bidirectional stream: one response per request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PurityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDraw': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDraw,
                    request_deserializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawRequest.FromString,
                    response_serializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawResponse.SerializeToString,
            ),
            'StreamDraws': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDraws,
                    request_deserializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawRequest.FromString,
                    response_serializer=qbert0g_dot_proto_dot_purity__service__pb2.DrawResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qr_purity.PurityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qr_purity.PurityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PurityService:
    """Server-side integrated draw service (the QPI layer).

    One draw = one freshly measured raw block, integrated server-side
    against the source's frozen fingerprint baseline into a z-score and
    a uniform value u = Phi(z), served together with the device-pair
    coherence snapshot and the source's canonical purity label.

    Invariants carried over from the entropy seam:
    - sequence_id is echoed verbatim (commitment-nonce echo);
    - a success response never carries u outside (0, 1) — the server
    clamps to (1e-10, 1 - 1e-10), so u = 0.0 on the wire is
    unambiguously "absent";
    - coherence_valid = false whenever the coherence gate cannot be
    computed (monitor disabled, stale, or never computed) — never a
    fake zero.

    """

    @staticmethod
    def GetDraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qr_purity.PurityService/GetDraw',
            qbert0g_dot_proto_dot_purity__service__pb2.DrawRequest.SerializeToString,
            qbert0g_dot_proto_dot_purity__service__pb2.DrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDraws(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/qr_purity.PurityService/StreamDraws',
            qbert0g_dot_proto_dot_purity__service__pb2.DrawRequest.SerializeToString,
            qbert0g_dot_proto_dot_purity__service__pb2.DrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
