"""CLI: `sources list` and `profiles pull` + the provenance-replay proof.

Sync tests on purpose — these subcommands call ``asyncio.run`` internally,
so they must not execute inside an already-running event loop.

The acceptance slice is deliberately DISTRIBUTION-AGNOSTIC: no entropy or
uniformity threshold is ever a pass criterion on served output (matched,
fitted PRNG controls are legitimately non-uniform). The pipeline proof is
byte-identity: regenerate the served block offline from NOTHING but its
provenance record (seeds + stream_offset_bytes + the normative xnor).
"""

import json
from pathlib import Path

import yaml
from conftest import SEED_A, SEED_B

from qbert0g.cli import main, render_watch_sample
from qbert0g.controls import uniform_stream_bytes
from qbert0g.profiles import xnor


def _write_config(tmp_path: Path) -> Path:
    data = {
        "server": {"listen": "127.0.0.1:0"},
        "database": {"path": str(tmp_path / "cli.db")},
        "devices": [{"id": "mock-0", "type": "mock"}, {"id": "mock-1", "type": "mock"}],
        "controls": [
            {"id": "prng-a", "type": "prng_uniform", "seed": SEED_A},
            {"id": "prng-b", "type": "prng_uniform", "seed": SEED_B},
        ],
        "profiles": [
            {"id": "pp-match", "transform": "xnor", "inputs": ["prng-a", "prng-b"]},
            {"id": "raw-mock", "transform": "identity", "inputs": ["mock-0"]},
        ],
        "provenance": {"path": str(tmp_path / "provenance.jsonl")},
    }
    path = tmp_path / "config.yaml"
    path.write_text(yaml.safe_dump(data), encoding="utf-8")
    return path


class TestSourcesList:
    def test_lists_all_kinds_with_availability(self, tmp_path, capsys):
        config = _write_config(tmp_path)
        main(["sources", "--config", str(config), "list"])
        out = capsys.readouterr().out
        assert "mock-0" in out and "mock" in out
        assert "prng-a" in out and "prng" in out
        assert "pp-match" in out and "xnor" in out and "prng-a,prng-b" in out
        assert "ready" in out and "online" in out


class TestProfilesPull:
    def test_pull_writes_file_and_cli_provenance(self, tmp_path, capsys):
        config = _write_config(tmp_path)
        out_file = tmp_path / "raw.bin"
        main([
            "profiles", "--config", str(config), "pull",
            "--id", "raw-mock", "--bytes", "4096", "--out", str(out_file),
        ])
        assert out_file.stat().st_size == 4096
        record = json.loads(
            (tmp_path / "provenance.jsonl").read_text().splitlines()[-1]
        )
        assert record["protocol"] == "cli"
        assert record["source_id"] == "raw-mock"
        assert record["inputs"][0]["kind"] == "mock"

    def test_pp_match_pull_regenerates_from_provenance_alone(self, tmp_path):
        """Acceptance slice (spec §13, amended): ~1 MB through the full
        pipeline, regenerated byte-for-byte offline from the provenance
        record only. Deterministic, CI-friendly, no entropy threshold."""
        config = _write_config(tmp_path)
        out_file = tmp_path / "pp.bin"
        n = 1_000_000
        main([
            "profiles", "--config", str(config), "pull",
            "--id", "pp-match", "--bytes", str(n), "--out", str(out_file),
        ])
        served = out_file.read_bytes()
        assert len(served) == n

        # ── offline regeneration: ONLY the record + the normative xnor ──
        record = json.loads(
            (tmp_path / "provenance.jsonl").read_text().splitlines()[-1]
        )
        assert record["transform"] == "xnor"
        streams = [
            uniform_stream_bytes(
                int(fact["seed"], 16), fact["stream_offset_bytes"], record["served_bytes"]
            )
            for fact in record["inputs"]
        ]
        assert served == xnor(streams[0], streams[1])


class TestSourcesWatch:
    """`sources watch` — the bitstream sync viewer (spec §14 addendum)."""

    def test_golden_render_pair(self):
        # 0xFF agrees on all 8 bits; 0x0F vs 0xF0 disagrees on all 8.
        block, agree, total = render_watch_sample(
            ids=["dev-a", "dev-b"],
            chunks=[b"\xff\x0f", b"\xff\xf0"],
            capture_ns=[1_000, 3_000],
            render_ns=501_000,
            skew_ns=2_000,
        )
        assert block == (
            "dev-a  11111111 00001111  cap=1000ns  lat=500us\n"
            "agree  |||||||| ........  50.0% (running 50.0%)  dt=2us\n"
            "dev-b  11111111 11110000  cap=3000ns  lat=498us"
        )
        assert (agree, total) == (8, 16)

    def test_render_running_percentage_accumulates(self):
        block, _, _ = render_watch_sample(
            ids=["a", "b"],
            chunks=[b"\xff", b"\xff"],  # this row: 100% agreement
            capture_ns=[0, 0],
            render_ns=0,
            skew_ns=0,
            running_agree_bits=0,
            running_total_bits=8,  # prior row: 0% agreement
        )
        assert "100.0% (running 50.0%)" in block

    def test_golden_render_single_stream(self):
        block, agree, total = render_watch_sample(
            ids=["mock-0"],
            chunks=[b"\xb4"],
            capture_ns=[2_000],
            render_ns=12_000,
            skew_ns=None,
        )
        assert block == "mock-0  10110100  cap=2000ns  lat=10us"
        assert (agree, total) == (0, 0)  # no agreement accounting in single mode

    def test_watch_end_to_end_against_two_mocks(self, tmp_path, capsys):
        config = _write_config(tmp_path)
        main([
            "sources", "--config", str(config), "watch",
            "--ids", "mock-0,mock-1", "--rows", "3", "--interval", "0",
            "--bytes-per-row", "4",
        ])
        lines = capsys.readouterr().out.splitlines()
        blocks = [line for line in lines if line.startswith("mock-")]
        agree_lines = [line for line in lines if line.startswith("agree")]
        assert len(blocks) == 6  # 3 rows x 2 streams
        assert len(agree_lines) == 3
        for line in agree_lines:
            assert "running" in line and "dt=" in line
        # 4 bytes per row -> 32 bit columns, grouped 8 per byte
        assert blocks[0].count(" ") >= 3 and "cap=" in blocks[0] and "lat=" in blocks[0]

    def test_watch_single_stream_mode(self, tmp_path, capsys):
        config = _write_config(tmp_path)
        main([
            "sources", "--config", str(config), "watch",
            "--ids", "mock-0", "--rows", "2", "--interval", "0",
        ])
        lines = capsys.readouterr().out.splitlines()
        assert len(lines) == 2
        assert all(line.startswith("mock-0") for line in lines)
        assert not any("agree" in line for line in lines)
