"""CLI: `sources list` and `profiles pull` + the provenance-replay proof.

Sync tests on purpose — these subcommands call ``asyncio.run`` internally,
so they must not execute inside an already-running event loop.

The acceptance slice is deliberately DISTRIBUTION-AGNOSTIC: no entropy or
uniformity threshold is ever a pass criterion on served output (matched,
fitted PRNG controls are legitimately non-uniform). The pipeline proof is
byte-identity: regenerate the served block offline from NOTHING but its
provenance record (seeds + stream_offset_bytes + the normative xnor).
"""

import json
from pathlib import Path

import yaml
from conftest import SEED_A, SEED_B

from qbert0g.cli import main
from qbert0g.controls import uniform_stream_bytes
from qbert0g.profiles import xnor


def _write_config(tmp_path: Path) -> Path:
    data = {
        "server": {"listen": "127.0.0.1:0"},
        "database": {"path": str(tmp_path / "cli.db")},
        "devices": [{"id": "mock-0", "type": "mock"}],
        "controls": [
            {"id": "prng-a", "type": "prng_uniform", "seed": SEED_A},
            {"id": "prng-b", "type": "prng_uniform", "seed": SEED_B},
        ],
        "profiles": [
            {"id": "pp-match", "transform": "xnor", "inputs": ["prng-a", "prng-b"]},
            {"id": "raw-mock", "transform": "identity", "inputs": ["mock-0"]},
        ],
        "provenance": {"path": str(tmp_path / "provenance.jsonl")},
    }
    path = tmp_path / "config.yaml"
    path.write_text(yaml.safe_dump(data), encoding="utf-8")
    return path


class TestSourcesList:
    def test_lists_all_kinds_with_availability(self, tmp_path, capsys):
        config = _write_config(tmp_path)
        main(["sources", "--config", str(config), "list"])
        out = capsys.readouterr().out
        assert "mock-0" in out and "mock" in out
        assert "prng-a" in out and "prng" in out
        assert "pp-match" in out and "xnor" in out and "prng-a,prng-b" in out
        assert "ready" in out and "online" in out


class TestProfilesPull:
    def test_pull_writes_file_and_cli_provenance(self, tmp_path, capsys):
        config = _write_config(tmp_path)
        out_file = tmp_path / "raw.bin"
        main([
            "profiles", "--config", str(config), "pull",
            "--id", "raw-mock", "--bytes", "4096", "--out", str(out_file),
        ])
        assert out_file.stat().st_size == 4096
        record = json.loads(
            (tmp_path / "provenance.jsonl").read_text().splitlines()[-1]
        )
        assert record["protocol"] == "cli"
        assert record["source_id"] == "raw-mock"
        assert record["inputs"][0]["kind"] == "mock"

    def test_pp_match_pull_regenerates_from_provenance_alone(self, tmp_path):
        """Acceptance slice (spec §13, amended): ~1 MB through the full
        pipeline, regenerated byte-for-byte offline from the provenance
        record only. Deterministic, CI-friendly, no entropy threshold."""
        config = _write_config(tmp_path)
        out_file = tmp_path / "pp.bin"
        n = 1_000_000
        main([
            "profiles", "--config", str(config), "pull",
            "--id", "pp-match", "--bytes", str(n), "--out", str(out_file),
        ])
        served = out_file.read_bytes()
        assert len(served) == n

        # ── offline regeneration: ONLY the record + the normative xnor ──
        record = json.loads(
            (tmp_path / "provenance.jsonl").read_text().splitlines()[-1]
        )
        assert record["transform"] == "xnor"
        streams = [
            uniform_stream_bytes(
                int(fact["seed"], 16), fact["stream_offset_bytes"], record["served_bytes"]
            )
            for fact in record["inputs"]
        ]
        assert served == xnor(streams[0], streams[1])
